# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c65bc4e0f7232ee8e397ca8f218df23d2c7d5dc750cdf39093a41550c2a236db4736ff4b86c589ad6877a2319ffe8f19e041b0d4e4fceec378214f24eea7564

test:
  secret_key_base: 7f727304e41365fba45882babf1cf507b4a8478482ef022dcd1123449196588398c79a0897d84f7d16e21e360862231aac2c9c39b249a31898d4248419aeb10a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
